name: 'Codeowners review'
description: 'Github Actions helper for request reviews from codeowners.'
author: 'theScore Media'
inputs:
  codeowners_file_path:
    required: true
    description: 'Codeowners file path'
  ownership_json:
    required: true
    description: 'Team definition'
  github_token:
    required: true
    description: 'Token used to fetch info using Github API'
runs:
  using: 'node16'
  main: 'dist/index.js'  
